Release 0.1.6

diff --git a/bin/bashing b/bin/bashing
--- a/bin/bashing
+++ b/bin/bashing
@@ -1,6 +1,12 @@
 #!/bin/bash
-export __BASHING_VERSION='0.1.4'
-export __VERSION='0.1.5'
+# ---------------------------------------------
+# Artifact:     bashing/bashing
+# Version:      0.1.6
+# Date (UTC):   Tue Jun 11 12:07:18 UTC 2013
+# Generated by: bashing 0.1.6
+# ---------------------------------------------
+export __BASHING_VERSION='0.1.6'
+export __VERSION='0.1.6'
 export __ARTIFACT_ID='bashing'
 export __GROUP_ID='bashing'
 BASHING_ROOT=$(cd "$(dirname "$0")" && pwd)
@@ -26,64 +32,40 @@ SRC_PATH="$PROJECT_ROOT/src"
 CLI_PATH="$SRC_PATH/tasks"
 LIB_PATH="$SRC_PATH/lib"
 HID_PATH="$SRC_PATH/hidden-tasks"
-function getMeta() {
-    local path="$1"
-    local key="$2"
-    if  [ ! -s "$1" ]; then return 1; fi
-    sed '/^\s*$/d' "$path"\
-        | sed '/^\s*\([^#]\|#!\)/d'\
-        | sed 's/^\s*# \?//'\
-        | sed -n "/<$key>/,\$p"\
-        | sed -n "0,/<\/$key>/p"\
-        | sed "s/<\/\?$key>//g"
-}
-function print_out() {
-    if [ -z "$OUT" ]; then
-        echo "$@";
+RED="`tput setaf 1`"
+GREEN="`tput setaf 2`"
+YELLOW="`tput setaf 3`"
+BLUE="`tput setaf 4`"
+MAGENTA="`tput setaf 5`"
+CYAN="`tput setaf 6`"
+WHITE="`tput setaf 7`"
+RESET="`tput sgr0`"
+function colorize() {
+    if [[ "$USE_COLORS" != "no" ]]; then
+        c="$1"
+        shift
+        echo -n ${c}${@}${RESET};
     else
-        echo "$@" >> "$OUT"
+        shift
+        echo -n "$@";
     fi
 }
-function redirect_out() {
-    local line=""
-    while IFS='' read -r line; do
-        print_out "$line";
-    done
-}
-function sep() { 
-    if [[ "$COMPACT" != "yes" ]]; then
-        print_out -n "# ";  
-        print_out "$(head -c 45 /dev/zero | tr '\0' '-')"; 
-    fi
-}
-function comment() { 
-    if [[ "$COMPACT" != "yes" ]]; then print_out "# $@"; fi; 
-}
-function nl() { 
-    if [[ "$COMPACT" != "yes" ]]; then print_out ""; fi; 
-}
-function includeBashFile() {
-    if [ -s "$1" ] && bash -n "$1"; then
-        if [[ "$COMPACT" != "yes" ]]; then echo "# $1"; fi; 
-        sed '/^\s*#.*$/d' "$1" | sed '/^\s*$/d';
-    fi
-}
-RX_ID='[a-zA-Z][a-zA-Z0-9_-]*'
-RX_INT='\(0\|[1-9][0-9]*\)'
-RX_VERSION="$RX_INT\\.$RX_INT\\.$RX_INT\(-$RX_ID\\)\\?"
-RX_ARTIFACT_STRING="^\\s*\\(\\($RX_ID\\)\\/\\)\\?\\($RX_ID\\)\\s\\+\\($RX_VERSION\\)\\s*$"
-function artifactString() { head -n 1 "$PROJECT_FILE"; }
-function artifactGet() { echo "$1" | sed -n "s/$RX_ARTIFACT_STRING/\\$2/p"; }
-function artifactVersion() { artifactGet "$1" 4; }
-function artifactId() { artifactGet "$1" 3; }
-function artifactGroupId() { artifactGet "$1" 2; }
+function green() { colorize "${GREEN}" "${@}"; }
+function red() { colorize "${RED}" "${@}"; }
+function yellow() { colorize "${YELLOW}" "${@}"; }
+function blue() { colorize "${BLUE}" "${@}"; }
+function magenta() { colorize "${MAGENTA}" "${@}"; }
+function cyan() { colorize "${CYAN}" "${@}"; }
+function white() { colorize "${WHITE}" "${@}"; }
 function generateHeader() {
     print_out "#!/bin/bash"
     sep
-    comment " Artifact:     $GROUP_ID/$ARTIFACT_ID"
-    comment " Version:      $ARTIFACT_VERSION"
-    comment " Date (UTC):   $(date -u)"
-    comment " Generated by: bashing $BASHING_VERSION"
+    print_out "# $(head -c 45 /dev/zero | tr '\0' '-')"; 
+    print_out "# Artifact:     $GROUP_ID/$ARTIFACT_ID"
+    print_out "# Version:      $ARTIFACT_VERSION"
+    print_out "# Date (UTC):   $(date -u)"
+    print_out "# Generated by: bashing $BASHING_VERSION"
+    print_out "# $(head -c 45 /dev/zero | tr '\0' '-')"; 
     sep
 }
 function generateMetadata() {
@@ -120,7 +102,7 @@ function generateLibrary() {
     comment "Library"
     nl
     cd "$SRC_PATH";
-    find "./lib" -type f -name "*.sh" | includeLibFile
+    find "./lib" -type f -name "*.sh" | sort | includeLibFile
     if [[ "$?" != "0" ]]; then exit 1; fi
     sep
     cd "$CWD";
@@ -128,12 +110,12 @@ function generateLibrary() {
 function collectCliScripts() {
     if [ -d "$CLI_PATH" ]; then
         cd "$CLI_PATH"
-        find "." -type f -name "*.sh"
+        find "." -type f -name "*.sh" -not -size 0 | sort
         cd "$CWD"
     fi
     if [ -d "$HID_PATH" ]; then
         cd "$HID_PATH"
-        find "." -type f -name "*.sh"
+        find "." -type f -name "*.sh" -not -size 0 | sort
         cd "$CWD"
     fi
 }
@@ -274,6 +256,37 @@ function generateStandaloneTask() {
     genInclude "after-task.sh"
     genInclude "cleanup.sh"
 }
+function print_out() {
+    if [ -z "$OUT" ]; then
+        echo "$@";
+    else
+        echo "$@" >> "$OUT"
+    fi
+}
+function redirect_out() {
+    local line=""
+    while IFS='' read -r line; do
+        print_out "$line";
+    done
+}
+function sep() { 
+    if [[ "$COMPACT" != "yes" ]]; then
+        print_out -n "# ";  
+        print_out "$(head -c 45 /dev/zero | tr '\0' '-')"; 
+    fi
+}
+function comment() { 
+    if [[ "$COMPACT" != "yes" ]]; then print_out "# $@"; fi; 
+}
+function nl() { 
+    if [[ "$COMPACT" != "yes" ]]; then print_out ""; fi; 
+}
+function includeBashFile() {
+    if [ -s "$1" ] && bash -n "$1"; then
+        if [[ "$COMPACT" != "yes" ]]; then echo "# $1"; fi; 
+        sed '/^\s*#.*$/d' "$1" | sed '/^\s*$/d';
+    fi
+}
 function error() {
     echo -n "$(red "(ERROR)") " 1>&2
     echo "$@" 1>&2
@@ -296,31 +309,26 @@ function debug() {
         echo "$@";
     fi
 }
-RED="`tput setaf 1`"
-GREEN="`tput setaf 2`"
-YELLOW="`tput setaf 3`"
-BLUE="`tput setaf 4`"
-MAGENTA="`tput setaf 5`"
-CYAN="`tput setaf 6`"
-WHITE="`tput setaf 7`"
-RESET="`tput sgr0`"
-function colorize() {
-    if [[ "$USE_COLORS" != "no" ]]; then
-        c="$1"
-        shift
-        echo -n ${c}${@}${RESET};
-    else
-        shift
-        echo -n "$@";
-    fi
+function getMeta() {
+    local path="$1"
+    local key="$2"
+    if  [ ! -s "$1" ]; then return 1; fi
+    sed '/^\s*$/d' "$path"\
+        | sed '/^\s*\([^#]\|#!\)/d'\
+        | sed 's/^\s*# \?//'\
+        | sed -n "/<$key>/,\$p"\
+        | sed -n "0,/<\/$key>/p"\
+        | sed "s/<\/\?$key>//g"
 }
-function green() { colorize "${GREEN}" "${@}"; }
-function red() { colorize "${RED}" "${@}"; }
-function yellow() { colorize "${YELLOW}" "${@}"; }
-function blue() { colorize "${BLUE}" "${@}"; }
-function magenta() { colorize "${MAGENTA}" "${@}"; }
-function cyan() { colorize "${CYAN}" "${@}"; }
-function white() { colorize "${WHITE}" "${@}"; }
+RX_ID='[a-zA-Z][a-zA-Z0-9_-]*'
+RX_INT='\(0\|[1-9][0-9]*\)'
+RX_VERSION="$RX_INT\\.$RX_INT\\.$RX_INT\(-$RX_ID\\)\\?"
+RX_ARTIFACT_STRING="^\\s*\\(\\($RX_ID\\)\\/\\)\\?\\($RX_ID\\)\\s\\+\\($RX_VERSION\\)\\s*$"
+function artifactString() { head -n 1 "$PROJECT_FILE"; }
+function artifactGet() { echo "$1" | sed -n "s/$RX_ARTIFACT_STRING/\\$2/p"; }
+function artifactVersion() { artifactGet "$1" 4; }
+function artifactId() { artifactGet "$1" 3; }
+function artifactGroupId() { artifactGet "$1" 2; }
 GROUP_ID=""
 ARTIFACT_ID=""
 ARTIFACT_VERSION=""
@@ -396,10 +404,6 @@ success "Successfully initialized '$INIT_PATH'."
 exit 0
   return 0;
 }
-function cli_version() {
-echo "bashing $(yellow "$__VERSION") (bash $BASH_VERSION)"
-  return 0;
-}
 function cli_run() {
 CLI="$1"
 if [ -z "$CLI" ]; then
@@ -413,6 +417,7 @@ if [ ! -e "$path" ]; then fatal "No such Task: $CLI"; fi
 generateStandaloneTask "$SRC" | bash -s "$@" &
 wait "$!"
 st="$?"
+debug "Task exitted with status $st."
 exit "$st"
   return 0;
 }
@@ -441,6 +446,10 @@ if [[ "$1" == "--compress" ]]; then
     chmod +x "$TARGET_FILE_COMPRESSED" >& /dev/null
 fi
 exit 0
+  return 0;
+}
+function cli_version() {
+echo "bashing $(yellow "$__VERSION") (bash $BASH_VERSION)"
   return 0;
 }
 function cli_compile() {
@@ -495,6 +504,19 @@ if [[ "$BUILD_CLI" == "yes" ]]; then generateCliExit; fi
 cd "$CWD"
   return 0;
 }
+function cli_deploy() {
+path="$1"
+if [ -z "$path" ]; then path="$PROJECT_ROOT/bin"; fi
+__run "uberbash"
+src="$PROJECT_ROOT/target/$ARTIFACT_ID-$ARTIFACT_VERSION.sh"
+if [ ! -s "$src" ]; then fatal "Could not find Uberbash."; fi
+dst="$path/$ARTIFACT_ID"
+if ! mkdir -p "$path"; then fatal "Could not create $path."; fi
+verbose "Deploying to $dst ..."
+cp "$src" "$dst" 2> /dev/null || fatal "Could not copy $src to $dst ...";
+success "Deployed successfully."
+  return 0;
+}
 function cli_new_task() {
 task="$1"
 hidden="no"
@@ -513,19 +535,6 @@ echo "echo \"Hello from Task '$task'\"" >> "$path"
 success "Created Task '$task'."
   return 0;
 }
-function cli_deploy() {
-path="$1"
-if [ -z "$path" ]; then path="$PROJECT_ROOT/bin"; fi
-__run "uberbash"
-src="$PROJECT_ROOT/target/$ARTIFACT_ID-$ARTIFACT_VERSION.sh"
-if [ ! -s "$src" ]; then fatal "Could not find Uberbash."; fi
-dst="$path/$ARTIFACT_ID"
-if ! mkdir -p "$path"; then fatal "Could not create $path."; fi
-verbose "Deploying to $dst ..."
-cp "$src" "$dst" 2> /dev/null || fatal "Could not copy $src to $dst ...";
-success "Deployed successfully."
-  return 0;
-}
 function __run() {
   local pid=""
   local status=255
@@ -536,21 +545,21 @@ function __run() {
     "clean") cli_clean "$@" & local pid="$!";;
     "install") cli_install "$@" & local pid="$!";;
     "new") cli_new "$@" & local pid="$!";;
-    "version") cli_version "$@" & local pid="$!";;
     "run") cli_run "$@" & local pid="$!";;
     "uberbash") cli_uberbash "$@" & local pid="$!";;
+    "version") cli_version "$@" & local pid="$!";;
     "compile") cli_compile "$@" & local pid="$!";;
-    "new.task") cli_new_task "$@" & local pid="$!";;
     "deploy") cli_deploy "$@" & local pid="$!";;
+    "new.task") cli_new_task "$@" & local pid="$!";;
     "help")
       echo "Usage: bashing <task> [...]" 1>&2
       cat 1>&2 <<HELP
 
     clean     :  remove build results and cached data
     help      :  display this help message
-    install   :  deploy uberbash at \$HOME/.bin
+    install   :  deploy uberbash at $HOME/.bin
     new       :  initialize directories for a bashing project
-    run       :  run task in the projects context
+    run       :  run task in the project's context
     uberbash  :  create standalone bash script
     version   :  display version
 
@@ -558,7 +567,7 @@ HELP
       status=0
       ;;
     "version")
-      echo "bashing 0.1.5 (bash $BASH_VERSION)"
+      echo "bashing 0.1.6 (bash $BASH_VERSION)"
       status=0
       ;;
     *) echo "Unknown Command: $cmd" 1>&2;;
